
services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    ports:
      - "${SQL_PORT}:1433"
    volumes:
      - sql-datas:/var/opt/mssql

  backend:
    build:
      context: .
      dockerfile: ./API/Dockerfile
    ports:
      - "${API_PORT}:80"
    environment:
      - ConnectionStrings__AuthContextString=Server=sql,1433;Database=bingoGaru;User Id=SA;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True
    depends_on:
      - sql

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "${FRONTEND_PORT}:4200"
    depends_on:
      - backend

volumes:
  sql-datas: